defaults:
  - agent: fpot
  - env: ogbench_state
  - train: offline
  - eval: default
  - logging: default
  - _self_

seed: 0
experiment_name: offline_base

hydra:
  run:
    dir: .
  output_subdir: null
